import { $ } from "bun"
import { join } from "path"
import { zodToJsonSchema } from "zod-to-json-schema"
import { ConfigSchema } from "../schemas/hulla.schema"

async function generateSchema() {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const jsonSchema = zodToJsonSchema(ConfigSchema as any, {
    name: "Hulla Config Schema",
    nameStrategy: "title",
    target: "jsonSchema7",
    $refStrategy: "none", // Generate inline schema without $ref
  })

  // Extract the actual schema from definitions if $ref is used
  let finalSchema: typeof jsonSchema
  if ("$ref" in jsonSchema && jsonSchema.$ref && jsonSchema.definitions) {
    const refName = jsonSchema.$ref.replace("#/definitions/", "")
    finalSchema = {
      ...jsonSchema.definitions[refName],
      $schema: "http://json-schema.org/draft-07/schema#",
      description: "Configuration schema for Hulla CLI tool",
    } as typeof jsonSchema
  } else {
    finalSchema = {
      ...jsonSchema,
      $schema: "http://json-schema.org/draft-07/schema#",
      description: "Configuration schema for Hulla CLI tool",
    }
  }

  const schemaPath = join(process.cwd(), "schemas", "hulla.schema.json")
  await Bun.write(schemaPath, JSON.stringify(finalSchema, null, 2))
  console.log(`✓ Generated ${schemaPath}`)

  // Generate TypeScript types from JSON schema
  const typesPath = join(process.cwd(), "schemas", "hulla.types.ts")
  await $`bun json2ts -i ${schemaPath} -o ${typesPath}`.quiet()

  // Read the generated file and replace the type name
  const typesFile = Bun.file(typesPath)
  let typesContent = await typesFile.text()
  typesContent = typesContent.replace(
    /export interface HullaSchema/g,
    "export interface HullaConfigSchema"
  )

  // Update the comment to reflect the new source
  typesContent = typesContent.replace(
    /\/\*[\s\S]*?\*\/\s*export interface/g,
    `/**
 * This file is automatically generated from hulla.schema.ts via hulla.schema.json.
 * DO NOT MODIFY IT BY HAND. Instead, modify hulla.schema.ts and run bun gen:schema
 */
export interface`
  )

  // Append comment if not already present
  if (!typesContent.includes("// To update this file")) {
    typesContent += "\n// To update this file, run bun gen:schema\n"
  }

  await Bun.write(typesPath, typesContent)

  // Format the file with prettier
  await $`bun prettier --write ${typesPath}`.quiet()

  console.log(`✓ Generated ${typesPath}`)

  // Update .hulla/hulla.json to use local schema for testing
  const configPath = join(process.cwd(), ".hulla", "hulla.json")
  const configFile = Bun.file(configPath)
  if (await configFile.exists()) {
    const config = (await configFile.json()) as {
      $schema?: string
      cli: unknown
    }
    // Reconstruct with $schema first
    const updatedConfig: typeof config = {
      $schema: "../schemas/hulla.schema.json",
      cli: config.cli,
    }
    await Bun.write(configPath, JSON.stringify(updatedConfig, null, 2))
    console.log(`✓ Updated ${configPath} to use local schema`)
  }
}

generateSchema()
