import { $ } from "bun"
import { basename, join } from "path"
import { z, type ZodType } from "zod"
import { ConfigSchema } from "../schemas/hulla.schema"
import { UIConfigSchema } from "../schemas/ui.schema"

type SchemaTask = {
  schema: ZodType
  schemaPath: string
  typesPath: string
  interfaceName: string
  title: string
  description: string
  sourceSchemaFile: string
}

function normalizeGeneratedTypes(input: {
  content: string
  interfaceName: string
  sourceSchemaFile: string
}): string {
  let content = input.content.trim()

  const firstInterfaceMatch = content.match(
    /export interface\s+([A-Za-z_][A-Za-z0-9_]*)/
  )
  if (!firstInterfaceMatch) {
    throw new Error(
      `Unable to find root interface in generated types for ${input.interfaceName}`
    )
  }

  const firstInterfaceName = firstInterfaceMatch[1]
  if (firstInterfaceName !== input.interfaceName) {
    content = content.replace(
      new RegExp(`export interface\\s+${firstInterfaceName}`),
      `export interface ${input.interfaceName}`
    )
  }

  // Remove generated banner from json2ts output and prepend our own.
  content = content.replace(/^(?:\/\*[\s\S]*?\*\/\s*)+/, "")

  return `/**
 * This file is automatically generated from ${input.sourceSchemaFile} via ${basename(input.sourceSchemaFile, ".ts")}.json.
 * DO NOT MODIFY IT BY HAND. Instead, modify ${input.sourceSchemaFile} and run bun gen:schema
 */
${content}

// To update this file, run bun gen:schema
`
}

async function generateSchemaAndTypes(task: SchemaTask) {
  const jsonSchema = z.toJSONSchema(task.schema, {
    target: "draft-07",
  }) as Record<string, unknown>

  const finalSchema = {
    ...jsonSchema,
    title: task.title,
    $schema: "http://json-schema.org/draft-07/schema#",
    description: task.description,
  }

  await Bun.write(task.schemaPath, JSON.stringify(finalSchema, null, 2) + "\n")
  console.log(`✓ Generated ${task.schemaPath}`)

  await $`bun json2ts -i ${task.schemaPath} -o ${task.typesPath}`.quiet()

  const typesFile = Bun.file(task.typesPath)
  const rawTypes = await typesFile.text()
  const normalizedTypes = normalizeGeneratedTypes({
    content: rawTypes,
    interfaceName: task.interfaceName,
    sourceSchemaFile: task.sourceSchemaFile,
  })

  await Bun.write(task.typesPath, normalizedTypes)
  await $`bun prettier --write ${task.typesPath}`.quiet()
  console.log(`✓ Generated ${task.typesPath}`)
}

async function updateLocalConfigSchemaPath() {
  const configPath = join(process.cwd(), ".hulla", "hulla.json")
  const configFile = Bun.file(configPath)
  if (!(await configFile.exists())) {
    return
  }

  const config = (await configFile.json()) as {
    $schema?: string
    cli: unknown
    configs?: unknown
  }

  const updatedConfig: typeof config = {
    $schema: "../schemas/hulla.schema.json",
    cli: config.cli,
    ...(config.configs ? { configs: config.configs } : {}),
  }

  await Bun.write(configPath, JSON.stringify(updatedConfig, null, 2) + "\n")
  console.log(`✓ Updated ${configPath} to use local schema`)
}

async function generateSchema() {
  const cwd = process.cwd()

  await generateSchemaAndTypes({
    schema: ConfigSchema,
    schemaPath: join(cwd, "schemas", "hulla.schema.json"),
    typesPath: join(cwd, "schemas", "hulla.types.ts"),
    interfaceName: "HullaConfigSchema",
    title: "Hulla Config Schema",
    description: "Configuration schema for Hulla CLI tool",
    sourceSchemaFile: "hulla.schema.ts",
  })

  await generateSchemaAndTypes({
    schema: UIConfigSchema,
    schemaPath: join(cwd, "schemas", "ui.schema.json"),
    typesPath: join(cwd, "schemas", "ui.types.ts"),
    interfaceName: "UIProjectConfigSchema",
    title: "Hulla UI Config Schema",
    description: "UI package configuration schema for Hulla CLI",
    sourceSchemaFile: "ui.schema.ts",
  })

  await updateLocalConfigSchemaPath()
}

generateSchema()
