/**
 * This file is automatically generated from hulla.schema.ts via hulla.schema.json.
 * DO NOT MODIFY IT BY HAND. Instead, modify hulla.schema.ts and run bun gen:schema
 */
export interface HullaConfigSchema {
  [k: string]: unknown
}

// To update this file, run bun gen:schema
