/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface HullaConfigSchema {
  /**
   * JSON Schema reference
   */
  $schema?: string;
  cli: {
    scripts: {
      add: string;
      addDev: string;
      uninstall: string;
      upgrade: string;
    };
    packageManager?: string;
    cache?: boolean;
    logs?: boolean;
  };
}
// To update this file, run pnpm gen:schema
