/**
 * This file is automatically generated from ui.schema.ts via ui.schema.json.
 * DO NOT MODIFY IT BY HAND. Instead, modify ui.schema.ts and run bun gen:schema
 */
export interface UIProjectConfigSchema {
  $schema?: string
  version: number
  sources: string[]
  installs: {
    sourceUrl: string
    libraryName: string
    componentsRoot: string
    copyFilesRoot: string
    rootTsconfigPath?: string
    frameworks: {
      name: string
      templatePath: string
      outputPath: string
      tsconfigPath: string
    }[]
  }[]
  postAddUpdateStep: string
}

// To update this file, run bun gen:schema
